schema-version: 1.0
name: wordpress

dependencies:
  - name: httpd
    alias: apache
  - php:7
  - name: mariadb
    alias: sql

var:
  db:
    name: wordpressdb
    user: wordpress
    password: password

provision:
  - pkg: rsync
  - url:
      from: https://wordpress.org/latest.tar.gz
      after: rsync -avP {{ installDir }}/wordpress/ {{ apache.documentRoot }}/
  - folder: "{{ apache.documentRoot }}/wp-content/upgrade"
  - folder: "{{ apache.documentRoot }}/wp-content/uploads"
  - shell: init.sh
  - permission:
      paths: "{{ apache.documentRoot }}"
      owner: "{{ apache.owner }}"
      group: "{{ apache.group }}"
      recursive: true
  - copy:
      from: wp-config.php
      todir: "{{ apache.documentRoot }}"