schema-version: 1.0
name: wordpress

dependencies:
  - name: httpd
    alias: apache
  - php:7
  - sql:mysql-ce:8.0

var:
  db:
    name: WordPressDB
    user: WordPressUser
    password: WordPressPassword

provision:
  - url:
      from: https://wordpress.org/latest.tar.gz
      to: "{{ apache.documentRoot }}"
      after:
        inline: mv wordpress/* . && rmdir wordpress
        directory: "{{ apache.documentRoot }}"
  - folder: "{{ apache.documentRoot }}/wp-content/upgrade"
  - shell: init.sh
  - permission:
      paths: "{{ apache.documentRoot }}"
      owner: "{{ apache.owner }}"
      group: "{{ apache.group }}"
      recursive: true
  - copy:
      from: wp-config.php
      todir: "{{ apache.documentRoot }}"